blank_issues_enabled: false
contact_links:
  - name: Maintainers
    url: https://github.com/orgs/winccoa-tools-pack/people
    about: If none of the templates fit, contact the maintainers for guidance.
